### ISSUE TITLE
архитектура

### ISSUE THREAD

**Issue by corwinnn** [sina2104/python_project#10]
https://github.com/sina2104/python_project/blob/49a4c76545654e0ecbfe85f25e6375323464ce11/animal.py#L4

почему именно классы в классе?

**Comment by sina2104** [comment]
Я на этот вопрос предыдущий разпытался ответить. Я использовал классы только потому, что мне легче было работать с классами в классе play в tamagotchi. Можно конечно реализовать всё это без классов, но мне казолось, что лучше всего использовать классы, если нужно работать с аттрибутами каждого животного отдельно, и также в моем случае читаемость кода улучшится.

**Comment by corwinnn** [comment]
почему нельзя сделать, чтобы Cat и Dog наследовались от Pet? не понимаю, зачем Animal

**Comment by sina2104** [comment]
Хорошо, согласен, можно обойтись без анимала. Удалил класс Anmial и теперь напрямую с Cat и Dog работаю.
