### ISSUE TITLE
class

### ISSUE THREAD

**Issue by corwinnn** [sina2104/python_project#5]
https://github.com/sina2104/python_project/blob/17c7bf22a7c7d564ecf8d2f05a1f3c54f10edd34/animal.py#L11

Названия классов с большой буквы

Чем мотивирована логика использовать здесь класс?

**Comment by sina2104** [comment]
ну я сделал для каждого животного отдельный класс, потому что в классе play я отдельно работаю с аттрибутами каждого класса

**Comment by corwinnn** [comment]
почему нельзя, к примеру, объекты одного класса с разнными атрибутами?

**Comment by sina2104** [comment]
Наверное можно, но мне кажется, что если на классы разбить, то аттрибуты каждого животного будут в отдельном классе и таким образом аттрибуты будут как-то сгруппированы и легче будет с ними работать
