### ISSUE TITLE
if

### ISSUE THREAD

**Issue by corwinnn** [sina2104/python_project#6]
https://github.com/sina2104/python_project/blob/17c7bf22a7c7d564ecf8d2f05a1f3c54f10edd34/tamagotchi.py#L22

почему if,а не elif?
что произойдет, если введут другое число, например, 3?
а если не число?

**Comment by sina2104** [comment]
Хорошо, я это исправил. Я добавил словарь, чтобы для большое количество животных не нужно было 100 раз if написать.
