### ISSUE TITLE
магические константы

### ISSUE THREAD

**Issue by corwinnn** [sina2104/python_project#7]
https://github.com/sina2104/python_project/blob/bba78d58908c3cb18cbd6f1ef922438def066b85/pet.py#L27

**Comment by sina2104** [comment]
Я хотел, чтобы вероятность попадении 18 была выше. Таким образом нам не приходится очень долго ждать, пока наше животное будет голодным

**Comment by corwinnn** [comment]
тогда назови как-то константу 18, чтобы это было понятно и используй
